### ISSUE TITLE
Compatibility issue with Elasticsearch 1.5.1

### ISSUE THREAD

**Issue by wajahat-javaid** [spinscale/elasticsearch-opennlp-plugin#7]
It seems this plugin is not compatible with elasticsearch 1.5.1.
After plugin installation, I am facing the following Exception at elasticsearch startup:

[2015-05-07 16:22:14,384][INFO ][node                     ] [Hyppokri] version[1.5.1], pid[8976], build[5e38401/2015-04-09T13:41:35Z]
[2015-05-07 16:22:14,385][INFO ][node                     ] [Hyppokri] initializing ...
[2015-05-07 16:22:14,447][INFO ][plugins                  ] [Hyppokri] loaded [analysis-phonetic, marvel, opennlp], sites [marvel]
[2015-05-07 16:22:17,708][INFO ][node                     ] [Hyppokri] initialized
[2015-05-07 16:22:17,779][INFO ][node                     ] [Hyppokri] starting ...
{1.5.1}: Startup Failed ...
- ExecutionError[org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchException]
        ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/ElasticSearchException]
                NoClassDefFoundError[org/elasticsearch/ElasticSearchException]
                        ClassNotFoundException[org.elasticsearch.ElasticSearchException]
Exception in thread "Thread-1" java.lang.NullPointerException
        at org.elasticsearch.cluster.action.index.MappingUpdatedAction.stop(MappingUpdatedAction.java:108)
        at org.elasticsearch.node.internal.InternalNode.stop(InternalNode.java:287)
        at org.elasticsearch.node.internal.InternalNode.close(InternalNode.java:321)
        at org.elasticsearch.bootstrap.Bootstrap$1.run(Bootstrap.java:75)

**Comment by spinscale** [comment]
If you can, I propose to run this process in separation. This is one of the reasons why I havent updated the plugin in ages. You should rip off the code and put it into a preprocessing component.

First, you need to load the model into the heap of all of your elasticsearch nodes, which takes some considerable amount of memory. Second, updating the model (or even the plugin) requires a rolling cluster restart.
